### ISSUE TITLE
Nested dependencies of dependencies are not resolved

### ISSUE THREAD

**Issue by gandulf** [ksoichiro/gradle-eclipse-aar-plugin#5]
Hi, 
this is not really a big issue, and can be resolved manually, but I just wanted to let you know in case you are bored an need something to do ;-)

If I added a library using gradle that itself depends on another library this nested dependency ist currently not resolved.
In my case it is the following library:

compile 'com.heinrichreimersoftware.materialdrawer:library:1.4.2'

this one also needs the appcompat-v7 library from google. So after running generateEclipedependencies I have to add the generated appcompat library (which I need anyway) as library to the generated materialdrawer project.

**Comment by ksoichiro** [comment]
Hi,
does it still happen with the latest version (v0.1.1)?
It handles the nested dependencies ("transitive dependencies", technically), I think.

**Comment by tobykurien** [comment]
I can confirm that this is an issue, and really hampers the use of, for example, the android design support library. You have to manually edit the generated project and add dependencies to the dependent project (in this case the design support library). It would be great if these dependencies were added automatically, because they are already downloaded and created as eclipse projects.

**Comment by ksoichiro** [comment]
@tobykurien Sorry for my late reply.
(My router has been broken these days and couldn't check GitHub.)
I'll look into it later.

**Comment by benhylau** [comment]
I have been using v0.2.0 of this plugin to resolve transitive JARs and AARs, and exploding all AARs including those transitive ones. I guess this is resolved?

**Comment by tobykurien** [comment]
No it is not resolved. The problem is not exploding AARs, it is that some of the exploded AARs have dependencies to others, and these are not included in that project's classpath

**Comment by benhylau** [comment]
Let me clarify. I use the plugin to resolve multiple levels of dependencies. For example: `Artifact A -> Artifact B` where `Artifact B -> Artifact C`. When running this on Artifact A, all three artifacts are resolved and included. What does your Artifact B pom look like? Does it reference Artifact C?
